<a href="https://colab.research.google.com/github/simasaadi/toronto-water-analytics/blob/main/notebooks/01_data_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("Environment OK — libraries loaded successfully.")

Environment OK — libraries loaded successfully.

In [ ]:
import os

# Create folder if not exists
os.makedirs("/content/data/raw", exist_ok=True)

# Download the ZIP from GitHub
zip_url = "<https://github.com/simasaadi/toronto-water-analytics/blob/main/data/raw/TORONTO.AOC1.zip>"
zip_path = "/content/data/raw/TORONTO.AOC1.zip"

!wget -O {zip_path} {zip_url}

# Verify file is downloaded
!ls -lh /content/data/raw

/bin/bash: -c: line 1: syntax error near unexpected token `newline'
/bin/bash: -c: line 1: `wget -O /content/data/raw/TORONTO.AOC1.zip <https://github.com/simasaadi/toronto-water-analytics/blob/main/data/raw/TORONTO.AOC1.zip>'
total 0

In [ ]:

# Create folder if not exists
os.makedirs("/content/data/raw", exist_ok=True)

# Download the ZIP from GitHub
zip_url = "<https://github.com/simasaadi/toronto-water-analytics/blob/main/data/raw/TORONTO.AOC1.zip>"
zip_path = "/content/data/raw/TORONTO.AOC1.zip"

!wget -O {zip_path} {zip_url}

# Verify file is downloaded
!ls -lh /content/data/raw

/bin/bash: -c: line 1: syntax error near unexpected token `newline'
/bin/bash: -c: line 1: `wget -O /content/data/raw/TORONTO.AOC1.zip <https://github.com/simasaadi/toronto-water-analytics/blob/main/data/raw/TORONTO.AOC1.zip>'
total 0

In [ ]:
import os

# 1) Make sure the folder exists in Colab
os.makedirs("/content/data/raw", exist_ok=True)

# 2) Direct raw URL of your ZIP file on GitHub
zip_url = "https://github.com/simasaadi/toronto-water-analytics/raw/main/data/raw/TORONTO.AOC1.zip"

# 3) Where to save it in Colab
zip_path = "/content/data/raw/TORONTO.AOC1.zip"

# 4) Download from GitHub into Colab
!wget -O "$zip_path" "$zip_url"

# 5) Check that the file is there
!ls -lh /content/data/raw

--2025-11-21 04:27:16--  https://github.com/simasaadi/toronto-water-analytics/raw/main/data/raw/TORONTO.AOC1.zip
Resolving github.com (github.com)... 140.82.113.3
Connecting to github.com (github.com)|140.82.113.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/simasaadi/toronto-water-analytics/main/data/raw/TORONTO.AOC1.zip [following]
--2025-11-21 04:27:16--  https://raw.githubusercontent.com/simasaadi/toronto-water-analytics/main/data/raw/TORONTO.AOC1.zip
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 13453005 (13M) [application/zip]
Saving to: ‘/content/data/raw/TORONTO.AOC1.zip’

/content/data/raw/T 100%[===================>]  12.83M  --.-KB/s    in 0.03s

2025-11-21 04:27:16 (367 MB/s) - ‘/content/data/raw/TORONTO.AOC1.zip’ saved [13453005/13453005]

total 13M
-rw-r--r-- 1 root root 13M Nov 21 04:27 TORONTO.AOC1.zip

In [ ]:
import zipfile

zip_path = "/content/data/raw/TORONTO.AOC1.zip"

with zipfile.ZipFile(zip_path, "r") as z:
    z.extractall("/content/data/raw")

print("Files extracted:")
!ls -lh /content/data/raw

Files extracted:
total 235M
-rw-r--r-- 1 root root 222M Nov 21 04:28 TORONTO.AOC1.csv
-rw-r--r-- 1 root root  13M Nov 21 04:27 TORONTO.AOC1.zip

In [ ]:
import pandas as pd

csv_path = "/content/data/raw/TORONTO.AOC1.csv"
df = pd.read_csv(csv_path)

df.head()

/tmp/ipython-input-2689065503.py:4: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv_path)

,Id,DOI,DatasetName,MonitoringLocationID,MonitoringLocationName,MonitoringLocationLatitude,MonitoringLocationLongitude,MonitoringLocationHorizontalCoordinateReferenceSystem,MonitoringLocationType,ActivityType,ActivityMediaName,ActivityStartDate,ActivityStartTime,SampleCollectionEquipmentName,CharacteristicName,ResultValue,ResultUnit,ResultValueType
0,119886859,10.25976/zqwq-zh61,Swim Drink Fish Toronto Community Monitoring Hubs,4544,Lake Ontario:Humber Bay West Park,43.61564,-79.47722,UNKWN,Lake/Pond,Field Msr/Obs,Surface Water,7/25/2019,0:00:00,Probe/Sensor,"Temperature, water",15.0,deg C,Actual
1,119886893,10.25976/zqwq-zh61,Swim Drink Fish Toronto Community Monitoring Hubs,4544,Lake Ontario:Humber Bay West Park,43.61564,-79.47722,UNKWN,Lake/Pond,Field Msr/Obs,Surface Water,7/15/2021,0:00:00,Probe/Sensor,Conductivity,360.0,uS/cm,Actual
2,119886896,10.25976/zqwq-zh61,Swim Drink Fish Toronto Community Monitoring Hubs,4544,Lake Ontario:Humber Bay West Park,43.61564,-79.47722,UNKWN,Lake/Pond,Field Msr/Obs,Surface Water,7/18/2019,0:00:00,NaN,pH,7.8,NaN,Actual
3,119886916,10.25976/zqwq-zh61,Swim Drink Fish Toronto Community Monitoring Hubs,4544,Lake Ontario:Humber Bay West Park,43.61564,-79.47722,UNKWN,Lake/Pond,Field Msr/Obs,Surface Water,9/3/2020,0:00:00,Probe/Sensor,Conductivity,369.0,uS/cm,Actual
4,119886936,10.25976/zqwq-zh61,Swim Drink Fish Toronto Community Monitoring Hubs,4544,Lake Ontario:Humber Bay West Park,43.61564,-79.47722,UNKWN,Lake/Pond,Field Msr/Obs,Surface Water,9/17/2020,0:00:00,Probe/Sensor,Conductivity,324.0,uS/cm,Actual

In [ ]:
import pandas as pd

csv_path = "/content/data/raw/TORONTO.AOC1.csv"

# Load with explicit options (good practice for big files)
df = pd.read_csv(
    csv_path,
    low_memory=False
)

df.shape, df.columns

((841785, 18),
 Index(['Id', 'DOI', 'DatasetName', 'MonitoringLocationID',
        'MonitoringLocationName', 'MonitoringLocationLatitude',
        'MonitoringLocationLongitude',
        'MonitoringLocationHorizontalCoordinateReferenceSystem',
        'MonitoringLocationType', 'ActivityType', 'ActivityMediaName',
        'ActivityStartDate', 'ActivityStartTime',
        'SampleCollectionEquipmentName', 'CharacteristicName', 'ResultValue',
        'ResultUnit', 'ResultValueType'],
       dtype='object'))

In [ ]:
df.head()

,Id,DOI,DatasetName,MonitoringLocationID,MonitoringLocationName,MonitoringLocationLatitude,MonitoringLocationLongitude,MonitoringLocationHorizontalCoordinateReferenceSystem,MonitoringLocationType,ActivityType,ActivityMediaName,ActivityStartDate,ActivityStartTime,SampleCollectionEquipmentName,CharacteristicName,ResultValue,ResultUnit,ResultValueType
0,119886859,10.25976/zqwq-zh61,Swim Drink Fish Toronto Community Monitoring Hubs,4544,Lake Ontario:Humber Bay West Park,43.61564,-79.47722,UNKWN,Lake/Pond,Field Msr/Obs,Surface Water,7/25/2019,0:00:00,Probe/Sensor,"Temperature, water",15.0,deg C,Actual
1,119886893,10.25976/zqwq-zh61,Swim Drink Fish Toronto Community Monitoring Hubs,4544,Lake Ontario:Humber Bay West Park,43.61564,-79.47722,UNKWN,Lake/Pond,Field Msr/Obs,Surface Water,7/15/2021,0:00:00,Probe/Sensor,Conductivity,360.0,uS/cm,Actual
2,119886896,10.25976/zqwq-zh61,Swim Drink Fish Toronto Community Monitoring Hubs,4544,Lake Ontario:Humber Bay West Park,43.61564,-79.47722,UNKWN,Lake/Pond,Field Msr/Obs,Surface Water,7/18/2019,0:00:00,NaN,pH,7.8,NaN,Actual
3,119886916,10.25976/zqwq-zh61,Swim Drink Fish Toronto Community Monitoring Hubs,4544,Lake Ontario:Humber Bay West Park,43.61564,-79.47722,UNKWN,Lake/Pond,Field Msr/Obs,Surface Water,9/3/2020,0:00:00,Probe/Sensor,Conductivity,369.0,uS/cm,Actual
4,119886936,10.25976/zqwq-zh61,Swim Drink Fish Toronto Community Monitoring Hubs,4544,Lake Ontario:Humber Bay West Park,43.61564,-79.47722,UNKWN,Lake/Pond,Field Msr/Obs,Surface Water,9/17/2020,0:00:00,Probe/Sensor,Conductivity,324.0,uS/cm,Actual

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 841785 entries, 0 to 841784
Data columns (total 18 columns):
 #   Column                                                 Non-Null Count   Dtype
---  ------                                                 --------------   -----
 0   Id                                                     841785 non-null  int64
 1   DOI                                                    841785 non-null  object
 2   DatasetName                                            841785 non-null  object
 3   MonitoringLocationID                                   841785 non-null  object
 4   MonitoringLocationName                                 841785 non-null  object
 5   MonitoringLocationLatitude                             841785 non-null  float64
 6   MonitoringLocationLongitude                            841785 non-null  float64
 7   MonitoringLocationHorizontalCoordinateReferenceSystem  841785 non-null  object
 8   MonitoringLocationType                                 841785 non-null  object
 9   ActivityType                                           841785 non-null  object
 10  ActivityMediaName                                      841785 non-null  object
 11  ActivityStartDate                                      841785 non-null  object
 12  ActivityStartTime                                      798193 non-null  object
 13  SampleCollectionEquipmentName                          826839 non-null  object
 14  CharacteristicName                                     841785 non-null  object
 15  ResultValue                                            770611 non-null  float64
 16  ResultUnit                                             727998 non-null  object
 17  ResultValueType                                        841785 non-null  object
dtypes: float64(3), int64(1), object(14)
memory usage: 115.6+ MB

In [24]:
# Make column names lowercase with underscores
df.columns = (
    df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ", "_")
)

df.columns

Index(['id', 'doi', 'datasetname', 'monitoringlocationid',
       'monitoringlocationname', 'monitoringlocationlatitude',
       'monitoringlocationlongitude',
       'monitoringlocationhorizontalcoordinatereferencesystem',
       'monitoringlocationtype', 'activitytype', 'activitymedianame',
       'activitystartdate', 'activitystarttime',
       'samplecollectionequipmentname', 'characteristicname', 'resultvalue',
       'resultunit', 'resultvaluetype', 'activity_datetime', 'year', 'month',
       'dayofweek'],
      dtype='object')

In [23]:
# Parse date
df["activitystartdate"] = pd.to_datetime(
    df["activitystartdate"],
    errors="coerce"
)

# Some times may be missing; fill with midnight
time_str = df["activitystarttime"].fillna("00:00:00")

# Convert "hh:mm:ss" to a timedelta
time_delta = pd.to_timedelta(time_str)

# Full datetime
df["activity_datetime"] = df["activitystartdate"] + time_delta

# Time-based features
df["year"] = df["activity_datetime"].dt.year
df["month"] = df["activity_datetime"].dt.month
df["dayofweek"] = df["activity_datetime"].dt.day_name()

df[["activitystartdate", "activitystarttime", "activity_datetime", "year", "month", "dayofweek"]].head()

  activitystartdate activitystarttime activity_datetime  year  month dayofweek
0        2019-07-25           0:00:00        2019-07-25  2019      7  Thursday
1        2021-07-15           0:00:00        2021-07-15  2021      7  Thursday
2        2019-07-18           0:00:00        2019-07-18  2019      7  Thursday
3        2020-09-03           0:00:00        2020-09-03  2020      9  Thursday
4        2020-09-17           0:00:00        2020-09-17  2020      9  Thursday

In [22]:
# Latitude/longitude already numeric, but enforce just in case
df["monitoringlocationlatitude"] = pd.to_numeric(
    df["monitoringlocationlatitude"], errors="coerce"
)
df["monitoringlocationlongitude"] = pd.to_numeric(
    df["monitoringlocationlongitude"], errors="coerce"
)

# Result value (measurement)
df["resultvalue"] = pd.to_numeric(df["resultvalue"], errors="coerce")

df[["resultvalue", "resultunit"]].describe(include="all")

          resultvalue resultunit
count   770611.000000     727998
unique            NaN         26
top               NaN       mg/L
freq              NaN     457470
mean       161.514551        NaN
std       1701.890167        NaN
min       -892.000000        NaN
25%          0.440000        NaN
50%          7.600000        NaN
75%         75.100000        NaN
max     680000.000000        NaN

In [21]:
critical_cols = [
    "monitoringlocationname",
    "activity_datetime",
    "characteristicname",
    "resultvalue",
]

before = len(df)
df_clean = df.dropna(subset=critical_cols)
after = len(df_clean)

print(f"Rows before: {before:,}")
print(f"Rows after : {after:,}")
print(f"Removed    : {before - after:,}")

Rows before: 841,785
Rows after : 770,611
Removed    : 71,174

In [20]:
# Example: focus on some common characteristics
focus_chars = [
    "Temperature, water",
    "Conductivity",
    "pH",
    "Escherichia coli",
]

df_clean = df_clean[df_clean["characteristicname"].isin(focus_chars)]

df_clean["characteristicname"].value_counts()

characteristicname
Temperature, water    28989
pH                    18243
Conductivity           7914
Escherichia coli       7300
Name: count, dtype: int64

In [19]:
import os

clean_dir = "/content/data/cleaned"
os.makedirs(clean_dir, exist_ok=True)

clean_path = os.path.join(clean_dir, "toronto_aoc1_clean.csv")
df_clean.to_csv(clean_path, index=False)

print("Saved cleaned file to:", clean_path)
!ls -lh /content/data/cleaned

Saved cleaned file to: /content/data/cleaned/toronto_aoc1_clean.csv
total 20M
-rw-r--r-- 1 root root 20M Nov 21 05:29 toronto_aoc1_clean.csv

In [25]:
import os

clean_dir = "/content/data/cleaned"
os.makedirs(clean_dir, exist_ok=True)

clean_path = f"{clean_dir}/toronto_aoc1_clean.csv"

# If you already saved df_clean before, this line will overwrite with the latest version
df_clean.to_csv(clean_path, index=False)

!ls -lh /content/data/cleaned

total 231M
-rw-r--r-- 1 root root 231M Nov 21 05:32 toronto_aoc1_clean.csv

In [ ]:
from google.colab import drive
drive.mount('/content/drive')